/* AI Assist: This file configures global layout metadata and applies the project-wide font to all pages. */
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

/* AI Assist: Open Sans is loaded via Next.js font optimization to avoid CSS @import ordering/runtime issues. */
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* AI Assist: This function renders the document shell and applies the global Open Sans font class.
   Params: children - The nested page content rendered inside the layout.
   Returns: The root HTML structure for the app. */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
